version: 1.0.{build}
branches:
  only:
  - master
image:
- macOS
- Ubuntu
- Visual Studio 2019
platform: Any CPU
build_script:
- sh: >-
    cd http

    git clone https://github.com/uNetworking/uSockets

    cd ..

    make

    git checkout binaries

    cp dist/*.node .

    git add Ouroborus*

    git status

    git pull origin binaries

    git commit -a -m "Updated binaries" --allow-empty

    git push
